<?php

namespace Database\Seeders;

use App\Models\PemanfaatanBMN;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;

class PemanfaatanBMNSeeder extends Seeder
{
    public function run(): void
    {
        // Hapus data lama jika ada
        PemanfaatanBMN::query()->delete();

        $pemanfaatans = [
            // ===== SK Sewa =====
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/01/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Surya Maju Abadi',
                'alamat_objek' => 'Jl. Gatot Subroto No. 12, Kuningan, Jakarta Selatan',
                'latitude' => -6.241586,
                'longitude' => 106.830538,
                'deskripsi_objek' => 'Gedung perkantoran 5 lantai dengan fasilitas lengkap: AC sentral, lift, parkir bawah tanah, dan ruang meeting.',
                'luas_tanah' => 1250.50,
                'luas_bangunan' => 8500.75,
                'nilai_sewa_tahunan' => 3500000000,
                'tanggal_mulai' => '2023-01-15',
                'tanggal_berakhir' => '2025-01-14',
                'masa_pemanfaatan_bulan' => 24,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-001.pdf',
                'keterangan' => 'Kontrak sewa untuk kantor regional dengan opsi perpanjangan 2 tahun.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/02/MK/BMN/2024',
                'nama_pihak_ketiga' => 'CV. Mandiri Jaya Property',
                'alamat_objek' => 'Jl. Sudirman Kav. 52-53, SCBD, Jakarta Selatan',
                'latitude' => -6.224771,
                'longitude' => 106.807320,
                'deskripsi_objek' => 'Ruko komersial 3 lantai di area bisnis strategis, cocok untuk showroom dan retail.',
                'luas_tanah' => 450.25,
                'luas_bangunan' => 1350.80,
                'nilai_sewa_tahunan' => 1200000000,
                'tanggal_mulai' => '2022-06-01',
                'tanggal_berakhir' => '2024-05-31',
                'masa_pemanfaatan_bulan' => 24,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-002.pdf',
                'keterangan' => 'Sewa untuk usaha retail fashion dengan pajak terpisah.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/03/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Graha Indah Sejahtera',
                'alamat_objek' => 'Jl. TB Simatupang Kav. 10, Cilandak, Jakarta Selatan',
                'latitude' => -6.301592,
                'longitude' => 106.814224,
                'deskripsi_objek' => 'Gudang logistik dengan kapasitas 5000 m³, dilengkapi sistem keamanan 24 jam.',
                'luas_tanah' => 3500.00,
                'luas_bangunan' => 2000.50,
                'nilai_sewa_tahunan' => 850000000,
                'tanggal_mulai' => '2023-03-10',
                'tanggal_berakhir' => '2024-09-09', // Segera berakhir
                'masa_pemanfaatan_bulan' => 18,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-003.pdf',
                'keterangan' => 'Sewa gudang untuk penyimpanan barang elektronik.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/04/MK/BMN/2023',
                'nama_pihak_ketiga' => 'Berkah Abadi Group',
                'alamat_objek' => 'Jl. Prof. Dr. Satrio Kav. 18, Kuningan, Jakarta Selatan',
                'latitude' => -6.227889,
                'longitude' => 106.828478,
                'deskripsi_objek' => 'Lapangan parkir komersial kapasitas 150 kendaraan dengan sistem elektronik.',
                'luas_tanah' => 2800.75,
                'luas_bangunan' => null,
                'nilai_sewa_tahunan' => 450000000,
                'tanggal_mulai' => '2021-11-01',
                'tanggal_berakhir' => '2023-10-31', // Sudah berakhir
                'masa_pemanfaatan_bulan' => 24,
                'status' => 'Berakhir',
                'file_sk' => 'dokumen/sk-004.pdf',
                'keterangan' => 'Kontrak parkir untuk karyawan dan pengunjung gedung perkantoran.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/05/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Mega Bangunan Indonesia',
                'alamat_objek' => 'Jl. M.H. Thamrin No. 1, Menteng, Jakarta Pusat',
                'latitude' => -6.186486,
                'longitude' => 106.834091,
                'deskripsi_objek' => 'Kios makanan di area food court dengan kapasitas 50 kursi.',
                'luas_tanah' => 80.25,
                'luas_bangunan' => 80.25,
                'nilai_sewa_tahunan' => 180000000,
                'tanggal_mulai' => '2024-01-01',
                'tanggal_berakhir' => '2024-12-31',
                'masa_pemanfaatan_bulan' => 12,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-005.pdf',
                'keterangan' => 'Sewa kios untuk usaha kuliner dengan sistem bagi hasil.',
            ],

            // ===== Izin Penghunian =====
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/01/MK/BMN/2024',
                'nama_pihak_ketiga' => 'Yayasan Pendidikan Nasional',
                'alamat_objek' => 'Jl. Jend. Sudirman Kav. 60, Setiabudi, Jakarta Selatan',
                'latitude' => -6.230565,
                'longitude' => 106.817743,
                'deskripsi_objek' => 'Gedung sekolah 4 lantai dengan 24 ruang kelas, laboratorium, dan perpustakaan.',
                'luas_tanah' => 4200.50,
                'luas_bangunan' => 3200.25,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2023-07-01',
                'tanggal_berakhir' => '2028-06-30',
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-001.pdf',
                'keterangan' => 'Izin penggunaan untuk kegiatan pendidikan non-profit.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/02/MK/BMN/2024',
                'nama_pihak_ketiga' => 'RS Umum Dharma Husada',
                'alamat_objek' => 'Jl. Pangeran Antasari No. 134, Cilandak, Jakarta Selatan',
                'latitude' => -6.273186,
                'longitude' => 106.803301,
                'deskripsi_objek' => 'Gedung rumah sakit dengan 150 tempat tidur, IGD, dan ruang operasi.',
                'luas_tanah' => 8500.75,
                'luas_bangunan' => 12500.50,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2020-03-15',
                'tanggal_berakhir' => '2025-03-14',
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Diperpanjang',
                'file_sk' => 'dokumen/izin-002.pdf',
                'keterangan' => 'Izin penghunian untuk fasilitas kesehatan masyarakat.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/03/MK/BMN/2023',
                'nama_pihak_ketiga' => 'PT. Bank Rakyat Indonesia',
                'alamat_objek' => 'Jl. Veteran No. 8, Gambir, Jakarta Pusat',
                'latitude' => -6.172002,
                'longitude' => 106.837012,
                'deskripsi_objek' => 'Gedung kantor cabang bank dengan 3 lantai, ruang teller, dan ruang safe deposit.',
                'luas_tanah' => 1250.25,
                'luas_bangunan' => 3750.75,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2019-01-01',
                'tanggal_berakhir' => '2024-01-01', // Akan berakhir
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-003.pdf',
                'keterangan' => 'Izin penggunaan untuk kantor pelayanan publik perbankan.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/04/MK/BMN/2022',
                'nama_pihak_ketiga' => 'PT. Telekomunikasi Indonesia',
                'alamat_objek' => 'Jl. Daan Mogot KM. 11, Cengkareng, Jakarta Barat',
                'latitude' => -6.147562,
                'longitude' => 106.718854,
                'deskripsi_objek' => 'Menara telekomunikasi dengan tinggi 75 meter dan perangkat BTS.',
                'luas_tanah' => 250.50,
                'luas_bangunan' => 150.25,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2018-05-10',
                'tanggal_berakhir' => '2023-05-09', // Sudah berakhir
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Berakhir',
                'file_sk' => 'dokumen/izin-004.pdf',
                'keterangan' => 'Izin penggunaan untuk infrastruktur telekomunikasi.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/05/MK/BMN/2024',
                'nama_pihak_ketiga' => 'Koperasi Pegawai Kementerian',
                'alamat_objek' => 'Jl. Lapangan Banteng Timur No. 4, Gambir, Jakarta Pusat',
                'latitude' => -6.171548,
                'longitude' => 106.837841,
                'deskripsi_objek' => 'Gedung serbaguna 2 lantai untuk kegiatan koperasi dan pertemuan pegawai.',
                'luas_tanah' => 850.75,
                'luas_bangunan' => 1700.50,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2024-02-01',
                'tanggal_berakhir' => '2029-01-31',
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-005.pdf',
                'keterangan' => 'Izin penggunaan untuk kegiatan koperasi pegawai.',
            ],

            // ===== Data Tambahan =====
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/06/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Trans Retail Indonesia',
                'alamat_objek' => 'Jl. M.T. Haryono Kav. 16, Cawang, Jakarta Timur',
                'latitude' => -6.242535,
                'longitude' => 106.861629,
                'deskripsi_objek' => 'Supermarket dengan luas 5000 m², dilengkapi cold storage dan sistem kasir modern.',
                'luas_tanah' => 5200.50,
                'luas_bangunan' => 5000.25,
                'nilai_sewa_tahunan' => 2800000000,
                'tanggal_mulai' => '2023-09-01',
                'tanggal_berakhir' => '2026-08-31',
                'masa_pemanfaatan_bulan' => 36,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-006.pdf',
                'keterangan' => 'Sewa untuk usaha ritel modern dengan opsi perpanjangan 2x24 bulan.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/07/MK/BMN/2023',
                'nama_pihak_ketiga' => 'PT. Mitra Adiperkasa',
                'alamat_objek' => 'Jl. Panglima Polim No. 1, Kebayoran Baru, Jakarta Selatan',
                'latitude' => -6.243268,
                'longitude' => 106.800422,
                'deskripsi_objek' => 'Ruko 4 lantai untuk showroom otomotif dengan bengkel servis.',
                'luas_tanah' => 650.25,
                'luas_bangunan' => 2600.75,
                'nilai_sewa_tahunan' => 1950000000,
                'tanggal_mulai' => '2022-04-01',
                'tanggal_berakhir' => '2024-03-31', // Segera berakhir
                'masa_pemanfaatan_bulan' => 24,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-007.pdf',
                'keterangan' => 'Sewa untuk dealer resmi kendaraan bermotor.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/06/MK/BMN/2023',
                'nama_pihak_ketiga' => 'Universitas Indonesia',
                'alamat_objek' => 'Jl. Salemba Raya No. 4, Senen, Jakarta Pusat',
                'latitude' => -6.194431,
                'longitude' => 106.849604,
                'deskripsi_objek' => 'Kampus dengan 8 gedung kuliah, laboratorium, dan perpustakaan.',
                'luas_tanah' => 18500.50,
                'luas_bangunan' => 12500.75,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2020-08-01',
                'tanggal_berakhir' => '2030-07-31',
                'masa_pemanfaatan_bulan' => 120,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-006.pdf',
                'keterangan' => 'Izin penggunaan untuk kampus cabang universitas negeri.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/08/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Plaza Indonesia Realty',
                'alamat_objek' => 'Jl. M.H. Thamrin No. 28-30, Menteng, Jakarta Pusat',
                'latitude' => -6.193945,
                'longitude' => 106.823458,
                'deskripsi_objek' => 'Mall dengan 6 lantai, 200 tenant, cinema, dan food court.',
                'luas_tanah' => 18500.75,
                'luas_bangunan' => 75000.50,
                'nilai_sewa_tahunan' => 12500000000,
                'tanggal_mulai' => '2024-01-01',
                'tanggal_berakhir' => '2033-12-31',
                'masa_pemanfaatan_bulan' => 120,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-008.pdf',
                'keterangan' => 'Sewa jangka panjang untuk pusat perbelanjaan premium.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/09/MK/BMN/2022',
                'nama_pihak_ketiga' => 'PT. Astra International',
                'alamat_objek' => 'Jl. Gaya Motor Raya No. 8, Sunter, Jakarta Utara',
                'latitude' => -6.145678,
                'longitude' => 106.891234,
                'deskripsi_objek' => 'Pabrik dengan 4 lini produksi, gudang, dan kantor administrasi.',
                'luas_tanah' => 22500.50,
                'luas_bangunan' => 15000.25,
                'nilai_sewa_tahunan' => 8500000000,
                'tanggal_mulai' => '2020-01-01',
                'tanggal_berakhir' => '2024-12-31', // Akan berakhir
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-009.pdf',
                'keterangan' => 'Sewa untuk fasilitas produksi otomotif dengan sistem royalty.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/07/MK/BMN/2024',
                'nama_pihak_ketiga' => 'Puskesmas Kecamatan Tanah Abang',
                'alamat_objek' => 'Jl. KH. Mas Mansyur No. 30, Tanah Abang, Jakarta Pusat',
                'latitude' => -6.202450,
                'longitude' => 106.812523,
                'deskripsi_objek' => 'Pusat kesehatan masyarakat dengan 3 poli, ruang bersalin, dan apotek.',
                'luas_tanah' => 1200.75,
                'luas_bangunan' => 850.50,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2024-03-15',
                'tanggal_berakhir' => '2029-03-14',
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-007.pdf',
                'keterangan' => 'Izin penggunaan untuk fasilitas kesehatan pemerintah daerah.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/10/MK/BMN/2023',
                'nama_pihak_ketiga' => 'PT. Matahari Department Store',
                'alamat_objek' => 'Jl. Letjen S. Parman Kav. 21, Slipi, Jakarta Barat',
                'latitude' => -6.195123,
                'longitude' => 106.797456,
                'deskripsi_objek' => 'Toko serba ada dengan 5 lantai retail, kasir terpusat, dan ruang stok.',
                'luas_tanah' => 3200.50,
                'luas_bangunan' => 16000.75,
                'nilai_sewa_tahunan' => 4500000000,
                'tanggal_mulai' => '2023-06-01',
                'tanggal_berakhir' => '2026-05-31',
                'masa_pemanfaatan_bulan' => 36,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-010.pdf',
                'keterangan' => 'Sewa untuk department store dengan sistem revenue sharing.',
            ],
            [
                'jenis_pemanfaatan' => 'Izin Penghunian',
                'nomor_sk' => 'IZIN/08/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Pos Indonesia',
                'alamat_objek' => 'Jl. Gedung Kesenian No. 1, Pasar Baru, Jakarta Pusat',
                'latitude' => -6.167890,
                'longitude' => 106.834567,
                'deskripsi_objek' => 'Gedung kantor pos dengan counter layanan, ruang sorting, dan gudang paket.',
                'luas_tanah' => 1850.25,
                'luas_bangunan' => 2750.50,
                'nilai_sewa_tahunan' => null,
                'tanggal_mulai' => '2024-01-01',
                'tanggal_berakhir' => '2028-12-31',
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/izin-008.pdf',
                'keterangan' => 'Izin penggunaan untuk kantor layanan pos nasional.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/11/MK/BMN/2022',
                'nama_pihak_ketiga' => 'PT. Global Hotel Management',
                'alamat_objek' => 'Jl. Jend. Sudirman Kav. 10-11, Karet, Jakarta Selatan',
                'latitude' => -6.208763,
                'longitude' => 106.822456,
                'deskripsi_objek' => 'Hotel bintang 4 dengan 250 kamar, ballroom, dan fasilitas konferensi.',
                'luas_tanah' => 8500.75,
                'luas_bangunan' => 42500.25,
                'nilai_sewa_tahunan' => 18500000000,
                'tanggal_mulai' => '2019-01-01',
                'tanggal_berakhir' => '2023-12-31', // Sudah berakhir
                'masa_pemanfaatan_bulan' => 60,
                'status' => 'Berakhir',
                'file_sk' => 'dokumen/sk-011.pdf',
                'keterangan' => 'Kontrak sewa hotel dengan sistem management fee.',
            ],
            [
                'jenis_pemanfaatan' => 'SK Sewa',
                'nomor_sk' => 'SK/12/MK/BMN/2024',
                'nama_pihak_ketiga' => 'PT. Pertamina Retail',
                'alamat_objek' => 'Jl. D.I. Panjaitan Kav. 8, Cawang, Jakarta Timur',
                'latitude' => -6.245678,
                'longitude' => 106.867890,
                'deskripsi_objek' => 'SPBU dengan 8 pompa, minimarket, dan car wash.',
                'luas_tanah' => 1250.50,
                'luas_bangunan' => 350.25,
                'nilai_sewa_tahunan' => 650000000,
                'tanggal_mulai' => '2024-02-15',
                'tanggal_berakhir' => '2027-02-14',
                'masa_pemanfaatan_bulan' => 36,
                'status' => 'Aktif',
                'file_sk' => 'dokumen/sk-012.pdf',
                'keterangan' => 'Sewa untuk stasiun pengisian bahan bakar umum dengan bagi hasil.',
            ],
        ];

        foreach ($pemanfaatans as $data) {
            // Buat folder dokumen jika belum ada
            if (!Storage::disk('public')->exists('dokumen')) {
                Storage::disk('public')->makeDirectory('dokumen');
            }

            PemanfaatanBMN::create($data);
        }

        $this->command->info('✅ Seeder Pemanfaatan BMN berhasil ditambahkan!');
        $this->command->info('📊 Total data: ' . count($pemanfaatans));
        $this->command->info('🏢 SK Sewa: ' . collect($pemanfaatans)->where('jenis_pemanfaatan', 'SK Sewa')->count());
        $this->command->info('🏠 Izin Penghunian: ' . collect($pemanfaatans)->where('jenis_pemanfaatan', 'Izin Penghunian')->count());
        $this->command->info('✅ Status Aktif: ' . collect($pemanfaatans)->where('status', 'Aktif')->count());
        $this->command->info('⚠️ Segera Berakhir (<30 hari): ' . collect($pemanfaatans)->filter(function($item) {
            $endDate = \Carbon\Carbon::parse($item['tanggal_berakhir']);
            return $endDate->diffInDays(now()) <= 30 && $endDate->isFuture();
        })->count());
    }
}
