<?php

namespace Database\Seeders;

use App\Models\PenatausahaanBMN;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PenatausahaanBMNSeeder extends Seeder
{
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu
        DB::table('penatausahaan_bmns')->truncate();

        // Data contoh untuk BMN
        $penatausahaans = [
            // =========== TANAH ===========
            [
                'kode_barang' => '1.01.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Tanah Kantor Pusat Jakarta',
                'kategori' => 'Tanah',
                'spesifikasi' => 'Tanah strategis di pusat kota Jakarta, memiliki sertifikat hak pakai',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2010',
                'jumlah_unit' => 1,
                'satuan' => 'm²',
                'nilai_perolehan' => 50000000000,
                'nilai_buku' => 75000000000,
                'tanggal_perolehan' => '2010-05-15',
                'kondisi' => 'Baik',
                'lokasi' => 'Gedung Utama Kemenkeu',
                'pengguna' => 'Biro Manajemen BMN',
                'nomor_dokumen_kepemilikan' => 'SHGB No. 1234/JKT/2010',
                'luas' => 2500.50,
                'alamat_lengkap' => 'Jl. Dr. Wahidin Raya No. 1, Jakarta Pusat',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Tanah untuk kantor pusat Kementerian Keuangan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '1.01.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Tanah Kantor Wilayah Bandung',
                'kategori' => 'Tanah',
                'spesifikasi' => 'Tanah di area perkantoran Bandung',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2012',
                'jumlah_unit' => 1,
                'satuan' => 'm²',
                'nilai_perolehan' => 25000000000,
                'nilai_buku' => 35000000000,
                'tanggal_perolehan' => '2012-08-20',
                'kondisi' => 'Baik',
                'lokasi' => 'Kantor Wilayah Bandung',
                'pengguna' => 'Kanwil Kemenkeu Jabar',
                'nomor_dokumen_kepemilikan' => 'SHGB No. 567/BDG/2012',
                'luas' => 1500.75,
                'alamat_lengkap' => 'Jl. Asia Afrika No. 100, Bandung',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Tanah untuk kantor wilayah Bandung',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== GEDUNG & BANGUNAN ===========
            [
                'kode_barang' => '2.01.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Gedung Utama Kemenkeu',
                'kategori' => 'Gedung Bangunan',
                'spesifikasi' => 'Gedung 10 lantai dengan fasilitas lengkap, AC sentral, lift, sistem keamanan modern',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2015',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 300000000000,
                'nilai_buku' => 280000000000,
                'tanggal_perolehan' => '2015-03-10',
                'kondisi' => 'Baik',
                'lokasi' => 'Gedung Utama Kemenkeu',
                'pengguna' => 'Seluruh Unit Kemenkeu',
                'nomor_dokumen_kepemilikan' => 'IMB No. 123/2015',
                'luas' => 15000.00,
                'alamat_lengkap' => 'Jl. Dr. Wahidin Raya No. 1, Jakarta Pusat',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Gedung utama operasional Kementerian Keuangan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '2.01.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Gedung Aula Serbaguna',
                'kategori' => 'Gedung Bangunan',
                'spesifikasi' => 'Gedung 2 lantai untuk pertemuan dan acara seremonial, kapasitas 500 orang',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2018',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 75000000000,
                'nilai_buku' => 70000000000,
                'tanggal_perolehan' => '2018-07-22',
                'kondisi' => 'Baik',
                'lokasi' => 'Kompleks Kemenkeu Jakarta',
                'pengguna' => 'Bagian Umum',
                'nomor_dokumen_kepemilikan' => 'IMB No. 456/2018',
                'luas' => 2000.00,
                'alamat_lengkap' => 'Jl. Dr. Wahidin Raya No. 1, Jakarta Pusat',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Gedung untuk acara seremonial dan pertemuan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== RUMAH NEGARA ===========
            [
                'kode_barang' => '3.01.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Rumah Dinas Menteri Keuangan',
                'kategori' => 'Rumah Negara',
                'spesifikasi' => 'Rumah mewah 2 lantai, 5 kamar tidur, kolam renang, taman luas',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2010',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 150000000000,
                'nilai_buku' => 120000000000,
                'tanggal_perolehan' => '2010-01-05',
                'kondisi' => 'Baik',
                'lokasi' => 'Kawasan Menteng',
                'pengguna' => 'Menteri Keuangan',
                'nomor_dokumen_kepemilikan' => 'SHM No. 789/2010',
                'luas' => 2000.00,
                'alamat_lengkap' => 'Jl. Taman Suropati No. 10, Menteng, Jakarta',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Rumah dinas untuk Menteri Keuangan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '3.01.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Rumah Dinas Pejabat Eselon I',
                'kategori' => 'Rumah Negara',
                'spesifikasi' => 'Rumah tipe 120/200, 3 kamar tidur, 2 kamar mandi, garasi',
                'merk_type' => null,
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2012',
                'jumlah_unit' => 10,
                'satuan' => 'Unit',
                'nilai_perolehan' => 50000000000,
                'nilai_buku' => 45000000000,
                'tanggal_perolehan' => '2012-04-15',
                'kondisi' => 'Baik',
                'lokasi' => 'Kompleks Perumahan Dinas',
                'pengguna' => 'Pejabat Eselon I',
                'nomor_dokumen_kepemilikan' => 'SHM No. 111/2012',
                'luas' => 200.00,
                'alamat_lengkap' => 'Jl. Perumahan Dinas Kemenkeu No. 1-10, Jakarta',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Rumah dinas untuk pejabat eselon I',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== KENDARAAN OPERASIONAL ===========
            [
                'kode_barang' => '4.01.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Mobil Operasional Layanan',
                'kategori' => 'Kendaraan Dinas Operasional',
                'spesifikasi' => 'Toyota Innova 2.0G, warna putih, kapasitas 7 penumpang',
                'merk_type' => 'Toyota Innova 2.0G',
                'nomor_polisi' => 'B 1234 KEU',
                'tahun_pembuatan' => '2020',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 350000000,
                'nilai_buku' => 250000000,
                'tanggal_perolehan' => '2020-06-10',
                'kondisi' => 'Baik',
                'lokasi' => 'Pool Kendaraan Kemenkeu',
                'pengguna' => 'Bagian Umum',
                'nomor_dokumen_kepemilikan' => 'STNK No. 1234567890',
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Untuk operasional kegiatan sehari-hari',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '4.01.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Bus Mini Operasional',
                'kategori' => 'Kendaraan Dinas Operasional',
                'spesifikasi' => 'Mitsubishi L300, warna putih, kapasitas 15 penumpang',
                'merk_type' => 'Mitsubishi L300',
                'nomor_polisi' => 'B 5678 KEU',
                'tahun_pembuatan' => '2019',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 250000000,
                'nilai_buku' => 180000000,
                'tanggal_perolehan' => '2019-03-15',
                'kondisi' => 'Rusak Ringan',
                'lokasi' => 'Pool Kendaraan Kemenkeu',
                'pengguna' => 'Bagian Umum',
                'nomor_dokumen_kepemilikan' => 'STNK No. 0987654321',
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Dalam Perbaikan',
                'keterangan' => 'Untuk transportasi karyawan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== KENDARAAN JABATAN ===========
            [
                'kode_barang' => '4.02.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Mobil Dinas Menteri',
                'kategori' => 'Kendaraan Dinas Jabatan',
                'spesifikasi' => 'Toyota Alphard 3.5 V6, warna hitam, fitur keamanan lengkap',
                'merk_type' => 'Toyota Alphard 3.5 V6',
                'nomor_polisi' => 'B 9999 MEN',
                'tahun_pembuatan' => '2021',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 1200000000,
                'nilai_buku' => 1000000000,
                'tanggal_perolehan' => '2021-01-20',
                'kondisi' => 'Baik',
                'lokasi' => 'Sekretariat Menteri',
                'pengguna' => 'Menteri Keuangan',
                'nomor_dokumen_kepemilikan' => 'STNK No. 1122334455',
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Kendaraan dinas untuk Menteri Keuangan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '4.02.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Mobil Dinas Sekjen',
                'kategori' => 'Kendaraan Dinas Jabatan',
                'spesifikasi' => 'Toyota Camry 2.5V, warna hitam, interior leather',
                'merk_type' => 'Toyota Camry 2.5V',
                'nomor_polisi' => 'B 8888 SEK',
                'tahun_pembuatan' => '2020',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 800000000,
                'nilai_buku' => 650000000,
                'tanggal_perolehan' => '2020-09-05',
                'kondisi' => 'Baik',
                'lokasi' => 'Sekretariat Sekjen',
                'pengguna' => 'Sekretaris Jenderal',
                'nomor_dokumen_kepemilikan' => 'STNK No. 6677889900',
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Kendaraan dinas untuk Sekretaris Jenderal',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== KENDARAAN FUNGSIONAL ===========
            [
                'kode_barang' => '4.03.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Mobil Petugas Pemeriksaan',
                'kategori' => 'Kendaraan Dinas Fungsional',
                'spesifikasi' => 'Suzuki Ertiga 1.5, warna putih, dilengkapi peralatan pemeriksaan',
                'merk_type' => 'Suzuki Ertiga 1.5',
                'nomor_polisi' => 'B 7777 FUN',
                'tahun_pembuatan' => '2022',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 220000000,
                'nilai_buku' => 200000000,
                'tanggal_perolehan' => '2022-02-28',
                'kondisi' => 'Baik',
                'lokasi' => 'Direktorat Jenderal Pajak',
                'pengguna' => 'Tim Pemeriksa Pajak',
                'nomor_dokumen_kepemilikan' => 'STNK No. 5544332211',
                'luas' => null,
                'alamat_lengkap' => 'Gedung DJP Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Untuk kegiatan pemeriksaan lapangan',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '4.03.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Mobil Pengawalan Barang',
                'kategori' => 'Kendaraan Dinas Fungsional',
                'spesifikasi' => 'Isuzu Elf 125 PS, warna biru, dilengkapi brankas pengaman',
                'merk_type' => 'Isuzu Elf 125 PS',
                'nomor_polisi' => 'B 6666 BAR',
                'tahun_pembuatan' => '2021',
                'jumlah_unit' => 1,
                'satuan' => 'Unit',
                'nilai_perolehan' => 350000000,
                'nilai_buku' => 300000000,
                'tanggal_perolehan' => '2021-11-15',
                'kondisi' => 'Baik',
                'lokasi' => 'Direktorat Jenderal Bea Cukai',
                'pengguna' => 'Tim Pengawalan',
                'nomor_dokumen_kepemilikan' => 'STNK No. 9988776655',
                'luas' => null,
                'alamat_lengkap' => 'Gedung DJBC Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Untuk pengawalan barang berharga',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            // =========== PERALATAN KANTOR ===========
            [
                'kode_barang' => '5.01.01.01.001',
                'nup' => '001',
                'nama_barang' => 'Komputer Desktop',
                'kategori' => 'Peralatan Kantor',
                'spesifikasi' => 'Processor Intel Core i7-11700, RAM 16GB, SSD 512GB, Monitor 24 inch',
                'merk_type' => 'Dell OptiPlex 7090',
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2022',
                'jumlah_unit' => 50,
                'satuan' => 'Unit',
                'nilai_perolehan' => 15000000,
                'nilai_buku' => 12000000,
                'tanggal_perolehan' => '2022-04-01',
                'kondisi' => 'Baik',
                'lokasi' => 'Gedung Utama Kemenkeu',
                'pengguna' => 'Pegawai Kemenkeu',
                'nomor_dokumen_kepemilikan' => null,
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Untuk keperluan kerja pegawai',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kode_barang' => '5.01.01.01.002',
                'nup' => '002',
                'nama_barang' => 'Printer Multifungsi',
                'kategori' => 'Peralatan Kantor',
                'spesifikasi' => 'HP LaserJet MFP M428fdw, print/copy/scan/fax, jaringan wifi',
                'merk_type' => 'HP LaserJet M428fdw',
                'nomor_polisi' => null,
                'tahun_pembuatan' => '2023',
                'jumlah_unit' => 20,
                'satuan' => 'Unit',
                'nilai_perolehan' => 8000000,
                'nilai_buku' => 7500000,
                'tanggal_perolehan' => '2023-01-10',
                'kondisi' => 'Baik',
                'lokasi' => 'Setiap Lantai Gedung',
                'pengguna' => 'Seluruh Unit',
                'nomor_dokumen_kepemilikan' => null,
                'luas' => null,
                'alamat_lengkap' => 'Gedung Utama Kemenkeu',
                'status_aset' => 'Digunakan',
                'keterangan' => 'Printer untuk kebutuhan kantor',
                'foto_aset' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insert data ke database
        foreach ($penatausahaans as $data) {
            PenatausahaanBMN::create($data);
        }

        // Tambahkan data dummy tambahan menggunakan factory jika diperlukan
        $this->command->info('Seeder PenatausahaanBMN berhasil dijalankan!');
        $this->command->info('Total data: ' . count($penatausahaans));
    }
}
