<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PerencanaanBMN;
use Carbon\Carbon;

class PerencanaanBMNSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu
        PerencanaanBMN::truncate();

        $data = [
            // RP4 - Draft
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/001/BMN/2024',
                'judul' => 'Pengadaan Komputer dan Laptop untuk Kantor Pusat',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 50 unit komputer dan 30 unit laptop untuk mendukung kegiatan operasional di Kantor Pusat. Perangkat ini akan digunakan oleh staf di berbagai divisi untuk meningkatkan produktivitas kerja.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-15',
                'nilai_estimasi' => 2500000000,
                'volume' => 80,
                'satuan' => 'unit',
                'status' => 'Draft',
                'keterangan' => 'Dokumen masih dalam proses penyusunan oleh tim perencanaan',
                'file_dokumen' => null,
                'pembuat' => 'Budi Santoso',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/002/BMN/2024',
                'judul' => 'Renovasi Gedung Kantor Wilayah Jakarta',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Renovasi menyeluruh gedung kantor wilayah Jakarta yang meliputi perbaikan struktural, pengecatan ulang, dan penataan interior. Renovasi bertujuan untuk meningkatkan kenyamanan kerja dan citra institusi.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-10',
                'nilai_estimasi' => 15000000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Diajukan',
                'keterangan' => 'Sudah diajukan ke bagian pengadaan tanggal 15 Februari 2024',
                'file_dokumen' => null,
                'pembuat' => 'Siti Rahayu',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/003/BMN/2024',
                'judul' => 'Pembelian Kendaraan Dinas Operasional',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 5 unit kendaraan dinas untuk operasional lapangan. Kendaraan akan digunakan untuk monitoring, inspeksi, dan kegiatan luar kantor lainnya.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-05',
                'nilai_estimasi' => 3500000000,
                'volume' => 5,
                'satuan' => 'unit',
                'status' => 'Disetujui',
                'keterangan' => 'Telah disetujui oleh Kepala Biro pada tanggal 20 Maret 2024',
                'file_dokumen' => null,
                'pembuat' => 'Agus Wijaya',
                'pejabat_pengesah' => 'Dr. Ir. Ahmad Hidayat, M.Si.',
                'tanggal_pengesahan' => '2024-03-20',
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/004/BMN/2024',
                'judul' => 'Pengadaan Peralatan Laboratorium',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan peralatan laboratorium modern untuk mendukung kegiatan riset dan pengujian. Peralatan meliputi mikroskop digital, centrifuge, spektrofotometer, dan peralatan pendukung lainnya.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-20',
                'nilai_estimasi' => 1200000000,
                'volume' => 15,
                'satuan' => 'set',
                'status' => 'Ditolak',
                'keterangan' => 'Ditolak karena melebihi anggaran yang tersedia untuk divisi laboratorium',
                'file_dokumen' => null,
                'pembuat' => 'Dewi Kurnia',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/005/BMN/2023',
                'judul' => 'Peningkatan Sistem Jaringan Internet',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Upgrade sistem jaringan internet kantor dari 100 Mbps ke 1 Gbps dengan penambahan access point dan penguatan infrastruktur jaringan.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-11-10',
                'nilai_estimasi' => 850000000,
                'volume' => 1,
                'satuan' => 'paket',
                'status' => 'Selesai',
                'keterangan' => 'Proyek telah selesai dan beroperasi dengan baik sejak Januari 2024',
                'file_dokumen' => null,
                'pembuat' => 'Hendra Pratama',
                'pejabat_pengesah' => 'Prof. Dr. Sri Mulyani, SE., M.Si.',
                'tanggal_pengesahan' => '2023-11-25',
            ],
            // RP4 - Tambahan
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/006/BMN/2024',
                'judul' => 'Pengadaan Perabotan Kantor',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan meja, kursi, lemari arsip, dan perabotan kantor lainnya untuk ruangan baru di lantai 5.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-28',
                'nilai_estimasi' => 750000000,
                'volume' => 120,
                'satuan' => 'buah',
                'status' => 'Diajukan',
                'keterangan' => 'Menunggu persetujuan dari bagian logistik',
                'file_dokumen' => null,
                'pembuat' => 'Rina Astuti',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/007/BMN/2025',
                'judul' => 'Pembangunan Data Center',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pembangunan data center baru dengan kapasitas 50 rack server, dilengkapi sistem pendingin dan UPS yang memadai.',
                'tahun_anggaran' => 2025,
                'tanggal_dokumen' => '2024-04-01',
                'nilai_estimasi' => 28000000000,
                'volume' => 1,
                'satuan' => 'unit',
                'status' => 'Draft',
                'keterangan' => 'Dalam tahap studi kelayakan dan perencanaan detail',
                'file_dokumen' => null,
                'pembuat' => 'Eko Susanto',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            // RKBMN
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/001/BMN/2024',
                'judul' => 'Rehabilitasi Gedung Kantor Pusat',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Rehabilitasi menyeluruh gedung kantor pusat yang meliputi perbaikan atap, penggantian sistem listrik, dan perbaikan fasilitas umum.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-25',
                'nilai_estimasi' => 12500000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Disetujui',
                'keterangan' => 'Telah disetujui dan akan dimulai pada triwulan kedua 2024',
                'file_dokumen' => null,
                'pembuat' => 'Maya Indah',
                'pejabat_pengesah' => 'Drs. Bambang Soesatyo, M.M.',
                'tanggal_pengesahan' => '2024-02-15',
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/002/BMN/2024',
                'judul' => 'Penggantian Mesin dan Peralatan Usang',
                'kategori' => 'Pemindahtanganan',
                'deskripsi' => 'Penggantian mesin fotokopi, printer, scanner, dan peralatan kantor lainnya yang sudah usang dan tidak efisien.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-15',
                'nilai_estimasi' => 650000000,
                'volume' => 45,
                'satuan' => 'unit',
                'status' => 'Diajukan',
                'keterangan' => 'Diajukan untuk persetujuan pengadaan triwulan kedua',
                'file_dokumen' => null,
                'pembuat' => 'Joko Prasetyo',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/003/BMN/2024',
                'judul' => 'Pembangunan Gedung Baru',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pembangunan gedung baru 5 lantai untuk menampung pertumbuhan jumlah pegawai dan kebutuhan ruang kerja yang semakin meningkat.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-01',
                'nilai_estimasi' => 85000000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Draft',
                'keterangan' => 'Masih dalam tahap perencanaan arsitektur dan perhitungan anggaran',
                'file_dokumen' => null,
                'pembuat' => 'Linda Wati',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/004/BMN/2023',
                'judul' => 'Peningkatan Sarana dan Prasarana',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Peningkatan sarana olahraga, musholla, dan ruang istirahat untuk kesejahteraan pegawai.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-10-05',
                'nilai_estimasi' => 950000000,
                'volume' => 3,
                'satuan' => 'ruang',
                'status' => 'Selesai',
                'keterangan' => 'Proyek telah selesai dan dimanfaatkan oleh pegawai sejak Desember 2023',
                'file_dokumen' => null,
                'pembuat' => 'Budi Santoso',
                'pejabat_pengesah' => 'Ir. Dian Novianto, M.T.',
                'tanggal_pengesahan' => '2023-10-20',
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/005/BMN/2023',
                'judul' => 'Pengadaan Aset Tetap Baru',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan berbagai aset tetap baru seperti generator listrik, water treatment plant, dan sistem pengolahan limbah.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-09-15',
                'nilai_estimasi' => 3200000000,
                'volume' => 5,
                'satuan' => 'set',
                'status' => 'Ditolak',
                'keterangan' => 'Ditolak karena alasan teknis dan anggaran yang tidak mencukupi',
                'file_dokumen' => null,
                'pembuat' => 'Siti Rahayu',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            // RKBMN - Tambahan
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/006/BMN/2025',
                'judul' => 'Rehabilitasi Jalan Lingkungan Kantor',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Rehabilitasi jalan akses menuju kantor sepanjang 500 meter untuk meningkatkan aksesibilitas dan kenyamanan.',
                'tahun_anggaran' => 2025,
                'tanggal_dokumen' => '2024-03-20',
                'nilai_estimasi' => 1800000000,
                'volume' => 500,
                'satuan' => 'meter',
                'status' => 'Draft',
                'keterangan' => 'Masih dalam tahap perencanaan teknis',
                'file_dokumen' => null,
                'pembuat' => 'Agus Wijaya',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/007/BMN/2024',
                'judul' => 'Pengadaan Generator Listrik',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 2 unit generator listrik berkapasitas 500 kVA sebagai cadangan daya untuk seluruh gedung kantor.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-05',
                'nilai_estimasi' => 4500000000,
                'volume' => 2,
                'satuan' => 'unit',
                'status' => 'Disetujui',
                'keterangan' => 'Sudah disetujui, pengadaan akan dilakukan pada triwulan ketiga',
                'file_dokumen' => null,
                'pembuat' => 'Dewi Kurnia',
                'pejabat_pengesah' => 'Dra. Rini Marwati, M.Si.',
                'tanggal_pengesahan' => '2024-02-25',
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/008/BMN/2024',
                'judul' => 'Pembangunan Taman dan Landscaping',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Pembangunan taman dan landscaping di area halaman kantor untuk menciptakan lingkungan kerja yang nyaman dan asri.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-30',
                'nilai_estimasi' => 750000000,
                'volume' => 2000,
                'satuan' => 'm²',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai bulan Maret 2024 dan sudah dimanfaatkan',
                'file_dokumen' => null,
                'pembuat' => 'Hendra Pratama',
                'pejabat_pengesah' => 'Dr. Ir. Ahmad Hidayat, M.Si.',
                'tanggal_pengesahan' => '2024-02-10',
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/009/BMN/2024',
                'judul' => 'Pengadaan Sistem Keamanan',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan sistem keamanan terintegrasi meliputi CCTV, access control system, dan alarm untuk seluruh area kantor.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-10',
                'nilai_estimasi' => 1850000000,
                'volume' => 1,
                'satuan' => 'sistem',
                'status' => 'Diajukan',
                'keterangan' => 'Diajukan untuk persetujuan anggaran keamanan',
                'file_dokumen' => null,
                'pembuat' => 'Rina Astuti',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/010/BMN/2024',
                'judul' => 'Renovasi Sistem Plumbing',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Renovasi sistem perpipaan air bersih dan air kotor di seluruh gedung kantor untuk meningkatkan efisiensi dan mencegah kebocoran.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-20',
                'nilai_estimasi' => 3200000000,
                'volume' => 1,
                'satuan' => 'sistem',
                'status' => 'Ditolak',
                'keterangan' => 'Ditolak karena ada rencana renovasi menyeluruh gedung tahun depan',
                'file_dokumen' => null,
                'pembuat' => 'Eko Susanto',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
            ],
        ];

        // Tambahkan created_at dan updated_at
        foreach ($data as &$item) {
            $item['created_at'] = Carbon::now();
            $item['updated_at'] = Carbon::now();
        }

        // Masukkan data ke database
        PerencanaanBMN::insert($data);

        $this->command->info('Seeder PerencanaanBMN berhasil dijalankan!');
        $this->command->info('Total data: ' . PerencanaanBMN::count());

        // Tampilkan statistik
        $this->command->info("\nStatistik:");
        $this->command->info('Total Dokumen: ' . PerencanaanBMN::count());
        $this->command->info('RP4: ' . PerencanaanBMN::where('jenis_perencanaan', 'RP4')->count());
        $this->command->info('RKBMN: ' . PerencanaanBMN::where('jenis_perencanaan', 'RKBMN')->count());

        $totalNilai = PerencanaanBMN::sum('nilai_estimasi');
        $this->command->info('Total Nilai: Rp ' . number_format($totalNilai, 0, ',', '.'));

        $statuses = ['Draft', 'Diajukan', 'Disetujui', 'Ditolak', 'Selesai'];
        foreach ($statuses as $status) {
            $count = PerencanaanBMN::where('status', $status)->count();
            $this->command->info("Status {$status}: {$count}");
        }
    }
}
