<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PerencanaanBMN;
use Carbon\Carbon;

class PerencanaanBMNSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Kosongkan tabel terlebih dahulu
        PerencanaanBMN::truncate();

        $data = [
            // RP4 - 2024
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/001/BMN/2024',
                'judul' => 'Pengadaan Komputer dan Laptop untuk Kantor Pusat',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 50 unit komputer dan 30 unit laptop untuk mendukung kegiatan operasional di Kantor Pusat.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-15',
                'nilai_estimasi' => 2500000000,
                'volume' => 80,
                'satuan' => 'unit',
                'status' => 'Draft',
                'keterangan' => 'Dokumen masih dalam proses penyusunan',
                'file_dokumen' => null,
                'pembuat' => 'Budi Santoso',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 1, 15),
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/002/BMN/2024',
                'judul' => 'Renovasi Gedung Kantor Wilayah Jakarta',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Renovasi menyeluruh gedung kantor wilayah Jakarta.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-10',
                'nilai_estimasi' => 15000000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Diajukan',
                'keterangan' => 'Sudah diajukan ke bagian pengadaan',
                'file_dokumen' => null,
                'pembuat' => 'Siti Rahayu',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 2, 10),
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/003/BMN/2024',
                'judul' => 'Pembelian Kendaraan Dinas Operasional',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 5 unit kendaraan dinas untuk operasional lapangan.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-05',
                'nilai_estimasi' => 3500000000,
                'volume' => 5,
                'satuan' => 'unit',
                'status' => 'Disetujui',
                'keterangan' => 'Telah disetujui oleh Kepala Biro',
                'file_dokumen' => null,
                'pembuat' => 'Agus Wijaya',
                'pejabat_pengesah' => 'Dr. Ir. Ahmad Hidayat, M.Si.',
                'tanggal_pengesahan' => '2024-03-20',
                'created_at' => Carbon::create(2024, 3, 5),
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/004/BMN/2024',
                'judul' => 'Pengadaan Peralatan Laboratorium',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan peralatan laboratorium modern untuk mendukung kegiatan riset.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-20',
                'nilai_estimasi' => 1200000000,
                'volume' => 15,
                'satuan' => 'set',
                'status' => 'Ditolak',
                'keterangan' => 'Ditolak karena melebihi anggaran',
                'file_dokumen' => null,
                'pembuat' => 'Dewi Kurnia',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 1, 20),
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/005/BMN/2024',
                'judul' => 'Peningkatan Sistem Jaringan Internet',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Upgrade sistem jaringan internet kantor dari 100 Mbps ke 1 Gbps.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-04-01',
                'nilai_estimasi' => 850000000,
                'volume' => 1,
                'satuan' => 'paket',
                'status' => 'Selesai',
                'keterangan' => 'Proyek telah selesai dan beroperasi',
                'file_dokumen' => null,
                'pembuat' => 'Hendra Pratama',
                'pejabat_pengesah' => 'Prof. Dr. Sri Mulyani, SE., M.Si.',
                'tanggal_pengesahan' => '2024-04-15',
                'created_at' => Carbon::create(2024, 4, 1),
            ],

            // RP4 - 2023
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/001/BMN/2023',
                'judul' => 'Pengadaan Perabotan Kantor 2023',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan meja, kursi, lemari arsip untuk ruangan baru.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-06-15',
                'nilai_estimasi' => 750000000,
                'volume' => 120,
                'satuan' => 'buah',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai bulan Agustus 2023',
                'file_dokumen' => null,
                'pembuat' => 'Rina Astuti',
                'pejabat_pengesah' => 'Drs. Bambang Soesatyo, M.M.',
                'tanggal_pengesahan' => '2023-06-30',
                'created_at' => Carbon::create(2023, 6, 15),
            ],
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/002/BMN/2023',
                'judul' => 'Pembangunan Data Center 2023',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pembangunan data center baru dengan kapasitas 50 rack server.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-07-20',
                'nilai_estimasi' => 28000000000,
                'volume' => 1,
                'satuan' => 'unit',
                'status' => 'Disetujui',
                'keterangan' => 'Proyek sedang berjalan',
                'file_dokumen' => null,
                'pembuat' => 'Eko Susanto',
                'pejabat_pengesah' => 'Ir. Dian Novianto, M.T.',
                'tanggal_pengesahan' => '2023-08-05',
                'created_at' => Carbon::create(2023, 7, 20),
            ],

            // RP4 - 2022
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/001/BMN/2022',
                'judul' => 'Pemasangan CCTV Keamanan 2022',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pemasangan sistem CCTV di seluruh area kantor.',
                'tahun_anggaran' => 2022,
                'tanggal_dokumen' => '2022-05-10',
                'nilai_estimasi' => 650000000,
                'volume' => 1,
                'satuan' => 'sistem',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai Juli 2022',
                'file_dokumen' => null,
                'pembuat' => 'Maya Indah',
                'pejabat_pengesah' => 'Dra. Rini Marwati, M.Si.',
                'tanggal_pengesahan' => '2022-05-25',
                'created_at' => Carbon::create(2022, 5, 10),
            ],

            // RKBMN - 2024
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/001/BMN/2024',
                'judul' => 'Rehabilitasi Gedung Kantor Pusat',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Rehabilitasi menyeluruh gedung kantor pusat.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-01-25',
                'nilai_estimasi' => 12500000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Disetujui',
                'keterangan' => 'Akan dimulai pada triwulan kedua 2024',
                'file_dokumen' => null,
                'pembuat' => 'Joko Prasetyo',
                'pejabat_pengesah' => 'Dr. Ir. Ahmad Hidayat, M.Si.',
                'tanggal_pengesahan' => '2024-02-15',
                'created_at' => Carbon::create(2024, 1, 25),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/002/BMN/2024',
                'judul' => 'Penggantian Mesin dan Peralatan Usang',
                'kategori' => 'Pemindahtanganan',
                'deskripsi' => 'Penggantian mesin fotokopi, printer, scanner yang sudah usang.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-02-15',
                'nilai_estimasi' => 650000000,
                'volume' => 45,
                'satuan' => 'unit',
                'status' => 'Diajukan',
                'keterangan' => 'Diajukan untuk persetujuan pengadaan',
                'file_dokumen' => null,
                'pembuat' => 'Linda Wati',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 2, 15),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/003/BMN/2024',
                'judul' => 'Pembangunan Gedung Baru',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pembangunan gedung baru 5 lantai untuk menampung pegawai.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-01',
                'nilai_estimasi' => 85000000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Draft',
                'keterangan' => 'Masih dalam tahap perencanaan',
                'file_dokumen' => null,
                'pembuat' => 'Budi Santoso',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 3, 1),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/004/BMN/2024',
                'judul' => 'Peningkatan Sarana dan Prasarana',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Peningkatan sarana olahraga, musholla, dan ruang istirahat.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-03-10',
                'nilai_estimasi' => 950000000,
                'volume' => 3,
                'satuan' => 'ruang',
                'status' => 'Ditolak',
                'keterangan' => 'Ditolak karena prioritas rendah',
                'file_dokumen' => null,
                'pembuat' => 'Siti Rahayu',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 3, 10),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/005/BMN/2024',
                'judul' => 'Pengadaan Aset Tetap Baru',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan generator listrik dan sistem pengolahan limbah.',
                'tahun_anggaran' => 2024,
                'tanggal_dokumen' => '2024-04-05',
                'nilai_estimasi' => 3200000000,
                'volume' => 5,
                'satuan' => 'set',
                'status' => 'Disetujui',
                'keterangan' => 'Telah disetujui dan akan diproses',
                'file_dokumen' => null,
                'pembuat' => 'Agus Wijaya',
                'pejabat_pengesah' => 'Prof. Dr. Sri Mulyani, SE., M.Si.',
                'tanggal_pengesahan' => '2024-04-20',
                'created_at' => Carbon::create(2024, 4, 5),
            ],

            // RKBMN - 2023
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/001/BMN/2023',
                'judul' => 'Rehabilitasi Jalan Lingkungan Kantor 2023',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Rehabilitasi jalan akses menuju kantor sepanjang 500 meter.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-08-15',
                'nilai_estimasi' => 1800000000,
                'volume' => 500,
                'satuan' => 'meter',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai November 2023',
                'file_dokumen' => null,
                'pembuat' => 'Dewi Kurnia',
                'pejabat_pengesah' => 'Drs. Bambang Soesatyo, M.M.',
                'tanggal_pengesahan' => '2023-08-30',
                'created_at' => Carbon::create(2023, 8, 15),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/002/BMN/2023',
                'judul' => 'Pengadaan Generator Listrik 2023',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan 2 unit generator listrik berkapasitas 500 kVA.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-09-10',
                'nilai_estimasi' => 4500000000,
                'volume' => 2,
                'satuan' => 'unit',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai Desember 2023',
                'file_dokumen' => null,
                'pembuat' => 'Hendra Pratama',
                'pejabat_pengesah' => 'Ir. Dian Novianto, M.T.',
                'tanggal_pengesahan' => '2023-09-25',
                'created_at' => Carbon::create(2023, 9, 10),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/003/BMN/2023',
                'judul' => 'Pembangunan Taman dan Landscaping 2023',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Pembangunan taman dan landscaping di area halaman kantor.',
                'tahun_anggaran' => 2023,
                'tanggal_dokumen' => '2023-10-05',
                'nilai_estimasi' => 750000000,
                'volume' => 2000,
                'satuan' => 'm²',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai November 2023',
                'file_dokumen' => null,
                'pembuat' => 'Rina Astuti',
                'pejabat_pengesah' => 'Dra. Rini Marwati, M.Si.',
                'tanggal_pengesahan' => '2023-10-20',
                'created_at' => Carbon::create(2023, 10, 5),
            ],

            // RKBMN - 2022
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/001/BMN/2022',
                'judul' => 'Pengadaan Sistem Keamanan 2022',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan sistem keamanan terintegrasi meliputi CCTV.',
                'tahun_anggaran' => 2022,
                'tanggal_dokumen' => '2022-06-20',
                'nilai_estimasi' => 1850000000,
                'volume' => 1,
                'satuan' => 'sistem',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai September 2022',
                'file_dokumen' => null,
                'pembuat' => 'Eko Susanto',
                'pejabat_pengesah' => 'Dr. Ir. Ahmad Hidayat, M.Si.',
                'tanggal_pengesahan' => '2022-07-05',
                'created_at' => Carbon::create(2022, 6, 20),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/002/BMN/2022',
                'judul' => 'Renovasi Sistem Plumbing 2022',
                'kategori' => 'Pemanfaatan',
                'deskripsi' => 'Renovasi sistem perpipaan air bersih dan air kotor.',
                'tahun_anggaran' => 2022,
                'tanggal_dokumen' => '2022-07-15',
                'nilai_estimasi' => 3200000000,
                'volume' => 1,
                'satuan' => 'sistem',
                'status' => 'Selesai',
                'keterangan' => 'Proyek selesai Oktober 2022',
                'file_dokumen' => null,
                'pembuat' => 'Maya Indah',
                'pejabat_pengesah' => 'Prof. Dr. Sri Mulyani, SE., M.Si.',
                'tanggal_pengesahan' => '2022-07-30',
                'created_at' => Carbon::create(2022, 7, 15),
            ],

            // Data untuk 2025 (untuk chart perbandingan tahun)
            [
                'jenis_perencanaan' => 'RP4',
                'nomor_dokumen' => 'RP4/001/BMN/2025',
                'judul' => 'Pengadaan Komputer 2025',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pengadaan komputer untuk tahun anggaran 2025.',
                'tahun_anggaran' => 2025,
                'tanggal_dokumen' => '2024-09-01',
                'nilai_estimasi' => 2000000000,
                'volume' => 60,
                'satuan' => 'unit',
                'status' => 'Draft',
                'keterangan' => 'Perencanaan awal untuk 2025',
                'file_dokumen' => null,
                'pembuat' => 'Joko Prasetyo',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 9, 1),
            ],
            [
                'jenis_perencanaan' => 'RKBMN',
                'nomor_dokumen' => 'RKBMN/001/BMN/2025',
                'judul' => 'Pembangunan Gedung 2025',
                'kategori' => 'Penggunaan',
                'deskripsi' => 'Pembangunan gedung baru untuk 2025.',
                'tahun_anggaran' => 2025,
                'tanggal_dokumen' => '2024-09-15',
                'nilai_estimasi' => 50000000000,
                'volume' => 1,
                'satuan' => 'gedung',
                'status' => 'Draft',
                'keterangan' => 'Perencanaan awal untuk 2025',
                'file_dokumen' => null,
                'pembuat' => 'Linda Wati',
                'pejabat_pengesah' => null,
                'tanggal_pengesahan' => null,
                'created_at' => Carbon::create(2024, 9, 15),
            ],
        ];

        // Tambahkan updated_at untuk setiap item
        foreach ($data as &$item) {
            $item['updated_at'] = Carbon::now();
        }

        // Masukkan data ke database
        PerencanaanBMN::insert($data);

        $this->command->info('Seeder PerencanaanBMN berhasil dijalankan!');
        $this->command->info('Total data: ' . PerencanaanBMN::count());

        // Tampilkan statistik
        $this->command->info("\nStatistik:");
        $this->command->info('Total Dokumen: ' . PerencanaanBMN::count());
        $this->command->info('RP4: ' . PerencanaanBMN::where('jenis_perencanaan', 'RP4')->count());
        $this->command->info('RKBMN: ' . PerencanaanBMN::where('jenis_perencanaan', 'RKBMN')->count());

        $totalNilai = PerencanaanBMN::sum('nilai_estimasi');
        $this->command->info('Total Nilai: Rp ' . number_format($totalNilai, 0, ',', '.'));

        $statuses = ['Draft', 'Diajukan', 'Disetujui', 'Ditolak', 'Selesai'];
        foreach ($statuses as $status) {
            $count = PerencanaanBMN::where('status', $status)->count();
            $this->command->info("Status {$status}: {$count}");
        }
    }
}
